name: flutter_tdd
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

#IOS
version: 12.0.48+2

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_keyboard_visibility: ^6.0.0
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  freezed: ^2.3.2
  freezed_annotation: ^2.4.1
  tf_dio_cache: ^1.0.2
  dio: ^5.1.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  auto_route: ^7.8.4
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.0
  firebase_messaging: ^15.2.5
  firebase_core: ^3.13.0
  flutter_local_notifications: ^18.0.1
  flutter_phoenix: ^1.1.1
  animations: ^2.0.8
  google_fonts: ^6.1.0
  pin_code_fields: ^8.0.1
  url_launcher: 6.3.1
  url_launcher_ios: ^6.3.1
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1
  permission_handler: ^12.0.0+1
  file_picker: ^10.1.9
  flutter_svg: ^2.0.9
  #  country_calling_code_picker: ^2.0.1
  flutter_slidable: ^4.0.0
  get_it: ^7.6.4
  injectable: ^2.3.2
#  firebase_analytics: 11.4.5
  firebase_crashlytics: ^4.3.5
  google_maps_flutter: ^2.10.1
  geocode: ^1.0.3
  flutter_screenutil: ^5.9.0
  internet_connectivity_checker: ^1.0.2
  simple_connection_checker: ^0.2.1
  adaptive_theme: 3.4.1
  widget_and_text_animator: ^1.1.5
  collection: ^1.17.2
  process_run: ^0.14.1+3
  get: ^4.6.6
  shimmer: ^3.0.0
  intl: ^0.19.0
  intl_utils: ^2.8.6
  device_info_plus:
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  smooth_page_indicator: ^1.2.0+3
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  aescryptojs: ^1.0.0
  sticky_headers: ^0.3.0+2
  google_sign_in: ^6.2.2
  firebase_auth: ^5.5.2
  animated_bottom_navigation_bar: ^1.3.3
  clipboard: ^0.1.3
  readmore: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.8.7
  super_tooltip: ^2.0.8
  dotted_border: ^2.1.0
  flutter_switch: ^0.3.2
  flutter_rounded_date_picker: ^3.0.4
  flutter_holo_date_picker: ^2.0.0
  country_phone_validator: ^1.0.1
  html: ^0.15.4
  sign_in_with_apple: ^7.0.1
  path: ^1.9.0
  flutter_facebook_auth: ^7.0.1
  sheet: ^1.0.0
  share_plus: ^11.0.0
  webview_flutter: ^4.11.0
  voice_message_package: ^2.2.1
  flutter_sound: ^9.28.0
  package_info_plus: ^8.3.0
  step_progress_indicator: ^1.0.2
  flutter_rating_bar: ^4.0.1
  wheel_picker: ^0.1.1
  smooth_star_rating_null_safety: ^1.0.4+2
  infinite_scroll_pagination: ^4.0.0
  photo_view: ^0.15.0
  percent_indicator: ^4.2.4
  socket_io_client: 1.0.2
  jwt_decoder: ^2.0.1
  syncfusion_flutter_datepicker: 25.1.42
  flutter_time_picker_spinner: ^2.0.0
  toggle_switch: ^2.3.0
  circle_flags: ^5.0.0
  lecle_downloads_path_provider: ^0.0.2+8
  open_file: any
  oktoast: ^3.4.0
  sliver_sticky_collapsable_panel: ^3.0.0
  loading_animation_widget: ^1.2.0+4
  moneyhash_payment: ^3.0.0
  uni_country_city_picker: ^1.0.2
  flutter_sticky_header: ^0.7.0
  mime: any
  phone_numbers_parser: ^9.0.3
  card_swiper: ^3.0.1
  draggable_fab: ^0.1.4
  pull_to_refresh: ^2.0.0
  wakelock_plus: ^1.3.1
  open_file_macos: ^0.1.0
  animate_do: ^3.3.4
  shorebird_code_push: ^2.0.3
  font_awesome_flutter: ^10.8.0
  easy_pdf_viewer: ^1.0.8
  app_tracking_transparency: ^2.0.6+1
  flutter_alice: ^2.0.1
  overlay_support: ^2.1.0
  stream_chat_flutter: ^9.10.0
  stream_video: 0.10.0
  stream_video_flutter: ^0.10.0
  stream_video_push_notification: 0.10.0
  upgrader: ^11.4.0
  stream_chat_localizations: ^9.3.0
  flutter_contacts: ^1.1.7+1
  geolocator: ^11.0.0
  map: ^1.3.5+1
  flutter_new_badger: ^1.1.1
  app_links: ^6.4.0
  pro_image_editor: ^9.13.0
  firebase_remote_config: ^5.4.5
  photo_manager: ^3.0.0
  any_link_preview: ^3.0.3
  flutter_link_previewer: any
  syncfusion_flutter_gauges: ^25.2.7
  fl_chart: ^1.0.0
  pull_down_button: ^0.10.2
  contextmenu: ^3.0.0
  gradient_borders:
  amplitude_flutter: ^4.3.7
  sentry_flutter: ^9.6.0


dependency_overrides:
  intl: 0.18.0
  stream_video_push_notification:
    path: third_party/stream_video_push_notification
  value_layout_builder: ^0.5.0
  record_ios: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  auto_route_generator: ^7.3.2 
  injectable_generator: ^2.4.1
  flutter_lints: ^3.0.1


flutter_intl:
  main_locale: en
  enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - shorebird.yaml
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SaudiRiyalFont
      fonts:
        - asset: assets/fonts/SaudiRiyalFont.ttf
    - family: SFProEn
      fonts:
        - asset: assets/fonts/sf_text/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/fonts/sf_text/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/fonts/sf_text/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/sf_text/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/sf_text/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/sf_text/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_text/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/sf_text/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/sf_text/SF-Pro-Text-Black.otf
          weight: 900
    
    - family: SFArabic
      fonts:
        - asset: assets/fonts/SF-Arabic.ttf



        # - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

