/// Generated by AssetsRefGenerator on 2022/03/09
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrowBack = "assets/images/arrowBack.svg";
  static const String arrowRight = "assets/images/arrow_right.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String check = "assets/images/check.svg";
  static const String unseen = "assets/images/unseen.png";
  static const String read = "assets/images/read.svg";
  static const String marker = "assets/images/marker.png";
  static const String redirectLinkEn = "assets/images/redirect_link_en.svg";
  static const String redirectLinkAr = "assets/images/redirect_link_ar.svg";
  static const String arrowBackEn = "assets/images/arrowBackEn.svg";
  static const String arrowBackAr = "assets/images/arrowBackAr.svg";
  static const String heart = "assets/images/heart.svg";
  static const String heartSolid = "assets/images/heartSolid.svg";
  static const String arrowUpSolid = "assets/images/arrow_up_solid.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String password = "assets/images/password.svg";
  static const String offline = "assets/images/offline.png";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String errorSnackBar = "assets/images/error_snack_bar.svg";
  static const String warningSnackBar = "assets/images/warning_snack_bar.svg";
  static const String successSnackBar = "assets/images/success_snack_bar.svg";
  static const String nojomLogo = "assets/images/nojom_logo.svg";
  static const String nojomSlogan = "assets/images/nojom_slogan.svg";
  static const String backIcon = "assets/images/back_icon.svg";
  static const String closeEyeIcon = "assets/images/close_eye_icon.svg";
  static const String appleIcon = "assets/images/apple_icon.svg";
  static const String google = "assets/images/google.png";
  static const String googleIcon = "assets/images/google_icon.svg";
  static const String faceBookIcon = "assets/images/face_book_icon.svg";
  static const String confirmImage = "assets/images/confirm_image.svg";
  static const String onboardingThirdPageImage =
      "assets/images/onboarding_third_image.png";
  static const String onboardingThirdPageArImage =
      "assets/images/onboarding_third_image_ar.png";
  static const String onboardingSecondPageImage =
      "assets/images/onboarding_second_image.png";
  static const String onboardingSecondPageImageAr =
      "assets/images/onboarding_second_image_ar.png";
  static const String onboardingFirstPageImage =
      "assets/images/on_boarding_first_image.png";
  static const String onboardingFirstPageImageAr =
      "assets/images/onboarding_first_image_ar.png";
  static const String tikTokIcon = "assets/images/tik_tok_icon.svg";
  static const String snapChatIcon = "assets/images/snap_chat_icon.png";
  static const String userIcon = "assets/images/user_icon.svg";
  static const String uploadImageIcon = "assets/images/upload_image_icon.svg";
  static const String imagePlaceholder = "assets/images/image_placeholder.svg";
  static const String deleteImageIcon = "assets/images/delete_image.svg";
  static const String editImageIcon = "assets/images/edit_image_icon.svg";
  static const String instagramIcon = "assets/images/instagram_icon.svg";
  static const String searchIcon = "assets/images/search_icon.svg";
  static const String starsSearchIcon = "assets/images/stars_search_icon.svg";
  static const String searchIconPng = "assets/images/search_icon.png";
  static const String gridIcon = "assets/images/grid_icon.svg";
  static const String campaignIcon = "assets/images/campaign_icon.svg";
  static const String campaignIconPng = "assets/images/campaign_icon.png";
  static const String chatIcon = "assets/images/chat_icon.svg";
  static const String chatIconPng = "assets/images/chat_icon.png";
  static const String moreIcon = "assets/images/more_icon.svg";
  static const String arrowDownIcon = "assets/images/arrow_down_icon.svg";
  static const String rearrangeIcon = "assets/images/rearrange_icon.svg";
  static const String activeCampaignIcon =
      "assets/images/active_campaign_icon.png";
  static const String activeCampaignIconPng =
      "assets/images/active_campaign_icon.png";
  static const String activeChatIcon = "assets/images/active_chat_icon.svg";
  static const String activeStarIconPng =
      "assets/images/active_star_icon_png.png";
  static const String activeChatIconPng =
      "assets/images/active_chat_icon_png.png";
  static const String activeMoreIcon = "assets/images/active_more_icon.svg";
  static const String activeProfileIcon =
      "assets/images/active_profile_icon.svg";
  static const String mawthouqIcon = "assets/images/mawthouq_icon.svg";
  static const String videoPlayIcon = "assets/images/video_play_icons.svg";
  static const String youtubeIcon = "assets/images/youtube_icon.svg";
  static const String copyIcon = "assets/images/copy_icon.svg";
  static const String phoneIcon = "assets/images/phone_icon.svg";
  static const String termsConditions = "assets/images/terms.svg";
  static const String agencyIcon = "assets/images/nojom_agency_icon.svg";
  static const String locationIcon = "assets/images/location_icon.svg";
  static const String infoIcon = "assets/images/info_icon.svg";
  static const String emailIcon = "assets/images/email_icon.svg";
  static const String webIcon = "assets/images/web_icon.svg";
  static const String addressIcon = "assets/images/address_icon.svg";
  static const String arrowBackIcon = "assets/images/arrow_back_icon.svg";
  static const String arrowBackIos = "assets/images/arrow_back_ios.svg";
  static const String singleArrowDownIcon =
      "assets/images/single_arrow_down_icon.svg";
  static const String arrowDown = "assets/images/arrow_down.png";
  static const String nojomSloganAr = "assets/images/nojom_slogan_ar.svg";
  static const String videoEmptyPageImage =
      "assets/images/add_video_empty_page_image.svg";
  static const String moreLinearIcon = "assets/images/more_linear_icon.svg";
  static const String upSideDownIcon = "assets/images/up_side_down_icon.svg";
  static const String noPartnersImage = "assets/images/no_partners_image.svg";
  static const String noProductsImage = "assets/images/no_products_image.svg";
  static const String cloudUploadIcon = "assets/images/cloud_upload.svg";
  static const String warningIcon = "assets/images/warning_icon.svg";
  static const String workWithEmptyImage =
      "assets/images/work_with_empty_image.svg";
  static const String socialMediaEmptyImage =
      "assets/images/empty_social_page_image.svg";
  static const String noSocialMediaFound =
      "assets/images/no_socila_items_found.png";
  static const String emptyImageLogo = "assets/images/empty_iamge_icon.png";
  static const String nojomIcon = "assets/images/nojom_icon.png";
  static const String arrowBackArIcon = "assets/images/arrow_back_ar_icon.svg";
  static const String calenderIcon = "assets/images/calendar_icon.svg";
  static const String arrowForwardIcon = "assets/images/arrow_forward_icon.svg";
  static const String closeIcon = "assets/images/close_icon.svg";
  static const String nojomFloatingButtonIcon =
      "assets/images/nojom_floating_button_icon.svg";
  static const String callCenter = "assets/images/call_center.png";
  static const String letter = "assets/images/letter.svg";
  static const String whatsApp = "assets/images/whats_app.svg";
  static const String backArrow = "assets/images/back_arrow.svg";
  static const String chatMoreIcon = "assets/images/chat_more_icon.svg";
  static const String pinIcon = "assets/images/pin_icon.svg";
  static const String unreadIcon = "assets/images/unread_icon.svg";
  static const String muteIcon = "assets/images/mute_icon.svg";
  static const String optionsCloseIcon = "assets/images/options_close_icon.svg";
  static const String personIcon = "assets/images/person_icon.svg";
  static const String personIconPng = "assets/images/person_icon_png.png";
  static const String personNotActiveIconPng =
      "assets/images/person_inactive_png.png";
  static const String reportIcon = "assets/images/report_icon.svg";
  static const String selectedIcon = "assets/images/selected_icon.svg";
  static const String unselectedIcon = "assets/images/unselected_icon.svg";
  static const String fileMessageIcon = "assets/images/file_message_icon.svg";
  static const String microphoneIcon = "assets/images/microphone_icon.svg";
  static const String stickerIcon = "assets/images/sticker_icon.svg";
  static const String seenIcon = "assets/images/seen_icon.svg";
  static const String cameraIcon = "assets/images/camera_icon.svg";
  static const String photoIcon = "assets/images/photo_icon.svg";
  static const String documentIcon = "assets/images/document_icon.svg";
  static const String deleteIcon = "assets/images/delete_icon.svg";
  static const String deleteTrashIcon = "assets/images/icon-delete-trash.svg";

  static const String sendIcon = "assets/images/send_icon.svg";
  static const String playAudioIcon = "assets/images/play_audio_icon.svg";
  static const String micIcon = "assets/images/mic_icon.svg";
  static const String nojomVoiceLogo = "assets/images/nojom_voice_logo.png";
  static const String forwardIcon = "assets/images/forward_icon.svg";
  static const String verifiedCheck = "assets/images/verified_check.svg";
  static const String uploadIcon = "assets/images/upload_icon.svg";
  static const String folderIcon = "assets/images/folder_icon.svg";
  static const String buildingIcon = "assets/images/building_icon.svg";
  static const String totalIncomeIcon = "assets/images/total_income_icon.svg";
  static const String closeCampaignIcon =
      "assets/images/close_campaign_icon.svg";
  static const String inviteIcon = "assets/images/invite_icon.svg";
  static const String editProfileIcon = "assets/images/edit_profile_icon.svg";
  static const String editSimple = "assets/images/edit_simple.svg";
  static const String walletIcon = "assets/images/wallet_icon.svg";
  static const String verifiIcon = "assets/images/verifi_icon.svg";
  static const String passwordIcon = "assets/images/password_icon.svg";
  static const String arrowIcon = "assets/images/arrow_icon.svg";
  static const String themeModeIcon = "assets/images/theme_mode_icon.svg";
  static const String notificationIcon = "assets/images/notification_icon.svg";
  static const String markLocationIcon = "assets/images/mark_location_icon.svg";
  static const String langIcon = "assets/images/lang_icon.svg";
  static const String languageMoreIcon = "assets/images/languageMoreIcon.svg";
  static const String shareApp = "assets/images/share.svg";
  static const String shareStar = "assets/images/shareStar.svg";
  static const String currencyIcon = "assets/images/currency_icon.svg";
  static const String feedBackIcon = "assets/images/feedback_icon.svg";
  static const String logOutIcon = "assets/images/logout_icon.svg";
  static const String inviteFriendsIcon =
      "assets/images/invite_friends_icon.svg";
  static const String helpIcon = "assets/images/help_privacy_icon.svg";
  static const String transactionsArrows =
      "assets/images/transactions_arrows.svg";
  static const String withdrawArrow = "assets/images/withdraw_arrow.svg";
  static const String pendingAccessTime =
      "assets/images/pending_access_time.svg";
  static const String outGoingTransfer = "assets/images/out_going_transfer.svg";
  static const String rejected = "assets/images/rejected.svg";
  static const String pdf = "assets/images/pdf.svg";
  static const String remove = "assets/images/remove.svg";
  static const String wallet = "assets/images/wallet.svg";
  static const String safe = "assets/images/safe.svg";
  static const String addCard = "assets/images/add_card.svg";
  static const String visa = "assets/images/visa.svg";
  static const String nojom = "assets/images/nojom.svg";
  static const String congrats = "assets/images/congrats.svg";
  static const String checkEmail = "assets/images/check_email.svg";
  static const String addIcon = "assets/images/add_icon.svg";
  static const String chatWithUsIcon = "assets/images/chat_with_us_icon.svg";
  static const String faqIcon = "assets/images/faq.svg";
  static const String trashIcon = "assets/images/trash_icon.svg";
  static const String trashRed = "assets/images/trashRed.svg";
  static const String chatImage = "assets/images/chat_image.png";
  static const String shareLinkIcon = "assets/images/share_link_icon.svg";
  static const String fileIcon = "assets/images/file_icon.svg";
  static const String removeIcon = "assets/images/remove_icon.svg";
  static const String emptyFolder = "assets/images/empty_folder.png";
  static const String emptyChat = "assets/images/empty_chat.png";
  static const String starIconActive = "assets/images/star_icon_active.svg";
  static const String starIcon = "assets/images/star_icon.svg";
  static const String starIconPng = "assets/images/star_icon.png";
  static const String filterIcon = "assets/images/filter_icon.svg";
  static const String favorite = "assets/images/favorite.svg";
  static const String favoriteActive = "assets/images/favorite_active.svg";
  static const String addCircle = "assets/images/add_circle.svg";
  static const String visaIcon = "assets/images/visa.png";
  static const String masterCard = "assets/images/money.png";
  static const String linkedIn = "assets/images/linkedin.png";
  static const String sms = "assets/images/sms.svg";
  static const String email = "assets/images/email.svg";
  static const String messages = "assets/images/messages.png";
  static const String mail = "assets/images/email_icon.png";
  static const String exploreMore = "assets/images/more_icon.png";
  static const String vipLevel = "assets/images/vip_level.png";
  static const String silverLevel = "assets/images/sliver_level.png";
  static const String goldLevel = "assets/images/gold_level.png";
  static const String blueLevel = "assets/images/blue_level.png";
  static const String attachFile = "assets/images/attach_file.png";
  static const String greenCheck = "assets/images/green_check.svg";
  static const String pdfIcon = "assets/images/pdf_icon.svg";
  static const String leaveFeedBackIcon =
      "assets/images/leave_feed_back_icon.svg";
  static const String noCampaignsFoundImage = "assets/images/no_campaigns.png";
  static const String noFilterData = "assets/images/empty_filter.png";
  static const String security = "assets/images/security.png";
  static const String serviceIconGrey = "assets/images/serviceIconGrey.png";
  static const String serviceIconBlue = "assets/images/serviceIconBlue.png";
  static const String campaignTimeIcon = "assets/images/icon_campaign_time.svg";
  static const String campaignChatIcon = "assets/images/icon_campaign_chat.svg";
  static const String campaignCalenderIcon =
      "assets/images/icon_campaign_calendar.svg";
  static const String stepStatusSelected =
      "assets/images/step_status_selected.png";
  static const String stepStatusPending =
      "assets/images/step_status_pending.svg";
  static const String stepStatusDone = "assets/images/step_status_done.svg";
  static const String deliveredStatusIcon = "assets/images/delivered_icon.svg";
  static const String completedStatusIcon =
      "assets/images/completed_step_icon.svg";
  static const String approvedStatusIcon = "assets/images/approved_icon.svg";
  static const String requestedStatusIcon = "assets/images/requested_icon.svg";
  static const String emptyRateIcon = "assets/images/empty_rate_icon.svg";
  static const String fillRateIcon = "assets/images/fill_rate_icon.svg";
  static const String fillStarIcon = "assets/images/fill_star_icon.svg";
  static const String successIcon = "assets/images/success_icon.svg";
  static const String profileIcon = "assets/images/profileIcon.svg";
  static const String walletSettings = "assets/images/icon_setting_wallet.svg";
  static const String settingsRate = "assets/images/icon-setting-rates.svg";

  // static const String settingsInvoices = "assets/images/icon_invoices.svg";
  static const String openLinkIcon = "assets/images/open_link_icon.svg";
  static const String settingsInvoices = "assets/images/invoice.svg";
  static const String starRate = "assets/images/star.svg";
  static const String contact = "assets/images/contact.svg";
  static const String privacy = "assets/images/privacy.svg";
  static const String settings = "assets/images/settings.svg";
  static const String fileTypeBgIcon = "assets/images/file-type-bg-icon.svg";
  static const String shareBlue = "assets/images/shareBlue.svg";
  static const String shareBlack = "assets/images/shareBlack.png";
  static const String favOutlineBlue = "assets/images/favOutlineBlue.svg";
  static const String arrowUpBlue = "assets/images/arrowUpBlue.svg";
  static const String noOrdersCreatedImage =
      "assets/images/no_orders_created_image.svg";
  static const String aiLogoImage = "assets/images/ai_logo.png";
  static const String aiIcon = "assets/images/ai_icon.svg";
  static const String previousIcon = "assets/images/previous_icon.svg";
  static const String reGenerateIcon = "assets/images/re_generate_icon.svg";
  static const String noStarsImage = "assets/images/no_stars_image.svg";
  static const String creditCard = "assets/images/credit-card.svg";
  static const String applePay = "assets/images/applePay.svg";
  static const String editGrey = "assets/images/editGrey.svg";
  static const String editBlue = "assets/images/editBlue.svg";
  static const String lockGrey = "assets/images/lockGrey.svg";
  static const String saudiLogoBlack = "assets/images/saudiLogoBlack.svg";
  static const String saudiLogoGrey = "assets/images/saudiLogoGrey.svg";
  static const String shieldDollar = "assets/images/shield-dollar.svg";
  static const String sparkleColors = "assets/images/sparkleColors.svg";
  static const String sparkleWhite = "assets/images/sparkleWhite.svg";
  static const String blueChatIcon = "assets/images/blue_chat.svg";
  static const String noAttachmentsFound =
      "assets/images/no_attachments_found_image.svg";
  static const String aiAddStars = "assets/images/aiAddStars.png";
  static const String removeFileIcon = "assets/images/remove_file_icon.svg";
  static const String file = "assets/images/file.svg";
  static const String coinsPriceIcon = "assets/images/icon-coins-price.svg";
  static const String newChatIcon = "assets/images/new_chat_icon.svg";
  static const String dialogConfirmIcon =
      "assets/images/dialog_confirm_icon.svg";
  static const String userLoginIcon = "assets/images/user_login_icon.svg";
  static const String newUserIcon = "assets/images/new_user_icon.svg";
  static const String loginIcon = "assets/images/login_icon.svg";
  static const String influencerOverViewImage =
      "assets/images/influencer_over_view_image.png";
  static const String downloadIcon = "assets/images/download_icon.svg";
  static const String gradientSparkIcon =
      "assets/images/gradient_spark_icon.svg";
  static const String num1Image = "assets/images/num1.svg";
  static const String num2Image = "assets/images/num2.svg";
  static const String num3Image = "assets/images/num3.svg";
  static const String num4Image = "assets/images/num4.svg";
  static const String num5Image = "assets/images/num5.svg";
  static const String aiStarsImageAr = "assets/images/ai_stars_ar.png";
  static const String aiStarsImageEn = "assets/images/ai_stars_en.png";
  static const String askPaymentImageAr = "assets/images/ask_payment_ar.png";
  static const String askPaymentImageEn = "assets/images/ask_payment_en.png";
  static const String createCampAr = "assets/images/create_camp_ar.png";
  static const String createCampEn = "assets/images/create_camp_en.png";
  static const String receiveCampImageAr = "assets/images/revieve_camp_ar.png";
  static const String receiveCampImageEn = "assets/images/receive_camp_en.png";
  static const String trackingCampImageAr =
      "assets/images/tracking_camp_ar.png";
  static const String trackingCampImageEn =
      "assets/images/tracking_camp_en.png";
  static const String gradientBgImage1 = "assets/images/ai_gradiant1.png";
  static const String gradientBgImage2 = "assets/images/ai_gradiant2.png";
  static const String gradientBgImage3 = "assets/images/ai_gradiant3.png";
  static const String gradientBgImage4 = "assets/images/ai_gradiant4.png";
  static const String gradientBgImage5 = "assets/images/ai_gradiant5.png";
  static const String whiteGradient = "assets/images/icon-white-gradient.svg";
  static const String notVerifiedIcon = "assets/images/not-verified-icon.svg";
  static const String inProgressVerification =
      "assets/images/in-progress-verification.svg";
  static const String successGreen = "assets/images/success_green.svg";
  static const String verifyLogoRegistrationSvg =
      "assets/images/verify_logo_registration.svg";
  static const String verifyLogoRegistrationPng =
      "assets/images/verify_logo_registration.png";

  static const String messageChatCircle =
      "assets/images/message_chat_circle.svg";
  static const String shoppingCart = "assets/images/shopping_cart.svg";
  static const String starsBlue = "assets/images/stars_blue.svg";
  static const String userPRofileIcon = "assets/images/icon_user_profile.svg";
  static const String regIconBuilding = "assets/images/reg_icon_building.svg";
  static const String regIconFile = "assets/images/reg_icon_file.svg";
  static const String regIconLink = "assets/images/reg_icon_link.svg";
  static const String regIconMail = "assets/images/reg_icon_mail.svg";
  static const String regIconMessage = "assets/images/reg_icon_message.svg";
  static const String regIconPhone = "assets/images/reg_icon_phone.svg";
  static const String regIconStars = "assets/images/reg_icon_stars.svg";
  static const String regIconProfile = "assets/images/reg_icon_profile.svg";
  static const String walletInProgress =
      "assets/images/icon-wallet-in-progress.svg";
  static const String walletCompleted =
      "assets/images/icon-wallet-completed.svg";
  static const String walletAddMoney =
      "assets/images/icon-wallet-add-money.svg";
  static const String whatsappIcon = "assets/images/icon_whatsapp.svg";

  static const String reyal = "assets/images/reyal.svg";
  static const String contactChatIcon = "assets/images/contact-chat-icon.svg";
  static const String cameraChatIcon = "assets/images/camera-chat-icon.svg";
  static const String newLocationIcon = "assets/images/new-location-icon.svg";
  static const String imageChatIcon = "assets/images/image-chat-icon.svg";
  static const String fileChatIcon = "assets/images/file-chat-icon.svg";
  static const String mute = "assets/images/mute.svg";
  static const String archive = "assets/images/archive.svg";
  static const String archiveBorder = "assets/images/archive-border.svg";
  static const String cameraBorderIcon = "assets/images/camera-border.svg";
  static const String microphoneBorderIcon =
      "assets/images/microphone-border.svg";
  static const String unpinIcon = "assets/images/unpin.svg";
  static const String videoRecorderCall =
      "assets/images/video-recorder-call.svg";
  static const String phoneCall = "assets/images/phone-call.svg";
  static const String support = "assets/images/support.svg";

  static const String attachmentDownload =
      "assets/images/icon-attachment-download.svg";

  static const String linkExternal1 = "assets/images/icon-link-external1.svg";
  static const String markerPin = "assets/images/marker_pin.svg";
  static const String shieldTick = "assets/images/shield_tick.svg";
  static const String tags = "assets/images/tags.svg";
  static const String fatFileCheck = "assets/images/icon-fat-file-check.svg";
  static const String messageChat = "assets/images/message_chat.svg";
  static const String share = "assets/images/share_1.svg";
  static const String noAdsSection = "assets/images/icon-no-ads-section.png";
  static const String checkCirclebroken =
      "assets/images/icon-check-circle-broken.svg";

  static const String tagList = "assets/images/icon-tag-list.svg";
  static const String clockFastForward =
      "assets/images/icon-clock-fast-forward.svg";

  static const String filterGrid = "assets/images/icon-filter-grid.svg";
  static const String filterRow = "assets/images/icon-filter-rows.svg";
  static const String filterSettings = "assets/images/icon-filter-settings.svg";
  static const String noFavoriteIcon = "assets/images/no_fav_icon.png";
  static const String listsAvatar = "assets/images/lists_avatar.svg";
  static const String closeIconBlack = "assets/images/close_icon_black.svg";
  static const String clearIcon = "assets/images/clear_icon.svg";
  static const String plusSquare = "assets/images/plus-square.svg";
  static const String newArrowRight = "assets/images/new-arrow-right.svg";
  static const String verifyZeroServiceFees =
      "assets/images/icon-verify-zero-service-fee.png";
  static const String bluredPrice = "assets/images/blured_price.png";


  static const String homeTabSolid = "assets/images/home_solid.svg";
  static const String homeTab = "assets/images/home_tab.svg";
  static const String chatTabSolid = "assets/images/chat_solid.svg";
  static const String chatTab = "assets/images/chat_tab.svg";
  static const String starsTab = "assets/images/stars_tab.svg";
  static const String starsTabSolid = "assets/images/stars_solid.svg";
  static const String campaignTabSolid = "assets/images/campaign_solid.svg";
  static const String campaignTab = "assets/images/campaign_tab.svg";
  static const String userTabSolid = "assets/images/user_tab_solid.svg";
  static const String userTab = "assets/images/user_tab.svg";
  static const String downloadNogomFrame = "assets/images/download_nogom_fram.png";


}
